### ISSUE TITLE
Allow max-width to be configurable

### ISSUE THREAD

**Issue by jgrund** [jonaylor89/hist#1]
It would be useful to set a maximum width for histograms, in the cases where you don't want them to take up the entire viewport width.

**Comment by jonaylor89** [comment]
That's a good idea. If you wanna do a pull request to just add a like `set_max_width` function or something I will pull it in, otherwise it might be a while since it's finals season at my university.

**Comment by jonaylor89** [comment]
@jgrund I made a max_width property for the histogram struct that can be modified in case you don't want the width to be the entire viewport. (Just finished finals)
