### ISSUE TITLE
Use console crate for calculating size

### ISSUE THREAD

**Issue by jgrund** [jonaylor89/hist#2]
Use console crate for calculating size instead of termion, `console` is compatible with windows while termion is not.

https://docs.rs/console/0.9.1/console/struct.Term.html?search=get_size

**Comment by jonaylor89** [comment]
That link brings up _"No results :("_  on the rust docs

**Comment by jgrund** [comment]
Whoops, try this one: https://docs.rs/console/0.9.1/console/struct.Term.html#method.size
